#! /bin/sh

sxhkd &

bspc monitor HDMI-0  -d EMACS JEUX MAIL CFG
bspc monitor DVI-D-0  -d WEB MUS TOR CHAT
bspc config border_width         2
bspc config window_gap          16

bspc config top_padding          27
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config active_border_color \#0066ff
bspc config normal_border_color \#3366ff

xset r rate 200 100
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Clementine desktop='^2'
bspc rule -a signal desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a Emacs desktop='^5'
bspc rule -a Lutris desktop='^7'
bspc rule -a thunderbird desktop='^7'
bspc rule -a Steam desktop='^6'

feh --bg-fill ~/Images/wallpapers/minimmountains.jpg
bash ~/.config/polybar/launch.sh
bash ~/.screenlayout/one.sh
compton &
~/.config/bspwm/bspswallow &
