#! /bin/sh

sxhkd &

bspc monitor HDMI-0  -d I II III IV V VI VII VIII
bspc config border_width         2
bspc config window_gap          16

bspc config top_padding          20
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config active_border_color \#6600cc
bspc config normal_border_color \#3333aa

xset r rate 200 100
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs desktop='^2'
bspc rule -a Clementine desktop='^3'
bspc rule -a Steam desktop='^4'
bspc rule -a Lutris desktop='^5'

feh --bg-fill ~/Images/wallpapers/night.png
bash ~/.config/polybar/launch.sh
compton &
~/.config/bspwm/bspswallow &
