#! /bin/sh

sxhkd &

bspc monitor HDMI-0  -d I II III IV 
bspc monitor DVI-I-0 -d V VI VII
bspc config border_width         2
bspc config window_gap          12
bash ~/.config/polybar/launch.sh

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill Images/wallpapers/wall.png
compton
